# ~/.tmuxinator/base.yml

name: Shell
root: ~/

windows:
  - Main:
      layout: b9a2,265x74,0,0{171x74,0,0[171x25,0,0,0,171x48,0,26,2],93x74,172,0,3} 
      panes:
        - sleep 1 && clear
        - vim
        - htop -u chronos
  - Notes:
      panes:
        - sleep 5 && "vim" .NOTES
