# ~/.tmuxinator/base.yml

name: Shell
root: ~/

windows:
  - Main:
      layout: d969,265x70,0,0{168x70,0,0[168x21,0,0,0,168x48,0,22,1],96x70,169,0,2}
      panes:
        - sleep 1 && clear
        - vim
        - htop
  - Files:
      panes:
        - mc
  - Notes:
      panes:
        - sleep 5 && "vim" .NOTES
